[tox]
envlist = py312-django52, quality

[testenv]
setenv =
    DJANGO_SETTINGS_MODULE = test_settings
    PYTHONPATH = {toxinidir}
deps =
    django52: Django>=5.2,<5.3
    -rtest-requirements.txt
commands =
    python -Wd -m pytest {posargs}
    coverage report

[testenv:quality]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    django52: Django>=5.2,<6.0
    -rtest-requirements.txt
commands =
    pycodestyle organizations
    pylint --rcfile=pylintrc organizations

