[tox]
envlist = py312-django52, quality
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    DJANGO_SETTINGS_MODULE = test_settings
    PYTHONPATH = {toxinidir}
dependency_groups =
    django52: test
allowlist_externals = make
commands =
    make test PYTEST_ARGS="{posargs}"

[testenv:quality]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups = quality
allowlist_externals = make
commands =
    make quality

[pycodestyle]
ignore=E501,W503
# W503 is "line break after binary operator".
# We must disable either W503 or W504 ("line break before binary operator")
# if we want it to be at all possible to split conditionals over multiple lines.
# The choice to disable W503 instead of W504 was arbitrary.
max_line_length=119
exclude=settings,migrations
