# Generated by Django 3.2.20 on 2023-07-27 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_historicalorganizationcourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalorganization',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical organization', 'verbose_name_plural': 'historical organizations'},
        ),
        migrations.AlterModelOptions(
            name='historicalorganizationcourse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Link Course', 'verbose_name_plural': 'historical Link Courses'},
        ),
    ]
